server:
  port: 8085

spring:
  application:
    name: media-service
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
