server:
  port: 8084

spring:
  application:
    name: chat-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://service-discovery:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
